### ISSUE TITLE
cannot publish due to JSR compatibility issues

### ISSUE THREAD

**Issue by protiev** [axhxrx/validated-string#1]
hey @masonmark JSR says [get off the elephant tranquilizer](https://github.com/axhxrx/validated-string/actions/runs/12329984329/job/34414933026) you madman

i'll give it another go-round when i get back from the discotheque if you can fix those problemas

**Comment by masonmark** [comment]
Hmm, OK fine for the missing explicit return types but... I mean, maybe fuck this bit?

I mean I'll do it if it's really going to slow down every `tsc` build, but not if it's just to save on jsr.io's PG&E bill...

```
error[unsupported-destructuring]: found destructuring, which is not supported in the public API
 --> /home/runner/work/validated-string/validated-string/LowercaseAlphabeticString.ts:5:7
  | 
5 | const { factory, type } = ValidatedString.create(isLowercaseAlpha, {
  |       ^^^^^^^^^^^^^^^^^
  = hint: separate each destructured symbol into its own export statement

  info: destructuring can not be inferred by fast check
  docs: https://jsr.io/go/slow-type-unsupported-destructuring
```

**Comment by protiev** [comment]
well itsche [arguably the latter, but complicated](https://github.com/jsr-io/jsr/issues/444#issuecomment-2079772908), so I suggest you should just take one for the team (..?)

**Comment by masonmark** [comment]
Well, solving the destructuring thing requires a pretty grotesque mutilation of the public API. I'm not sure, I think I need to sleep on it. In principle, I guess I am OK if it's just a "library author" pain point but... I mean, compare:

### before:

```ts
const { factory, type } = ValidatedString.create(
  isAlphabeticOrUnderscoreOrHyphen,
  {
    name: 'AlphabeticOrUnderscoreOrHyphenString',
    description: 'must contain only letters (A-Z, a-z), underscores, or hyphens',
  },
);

export type AlphabeticOrUnderscoreOrHyphenString = typeof type;
export const AlphabeticOrUnderscoreOrHyphenString = factory;

```

### after

```ts

const JSRCompatibleFactory = ValidatedString.create(
  isAlphabeticOrUnderscoreOrHyphen,
  {
    name: 'AlphabeticOrUnderscoreOrHyphenString',
    description: 'must contain only letters (A-Z, a-z), underscores, or hyphens',
  },
);

const type = JSRCompatibleFactory.type;
const factory = JSRCompatibleFactory.factory;
```

😅 LOL, OK, OK, I guess you're right, it's not *that* big of a deal (assuming this solves the issue — additional out-of-band type checking is maybe cool, additional out-of-band linting requirements that only show up during the publishing phase, less so...)


### update

The PR is now closed but just to correct the record, it did become kind of a bloodbath:

```ts
ValidatedString.create(
  isAlphabeticOrUnderscoreOrHyphen,
  {
    name: 'AlphabeticOrUnderscoreOrHyphenString',
    description: 'must contain only letters (A-Z, a-z), underscores, or hyphens',
  },
);

const type: ValidatedString<typeof isAlphabeticOrUnderscoreOrHyphen> = JSRCompatibleFactory.type;
const factory: ValidatedStringFactory<typeof isAlphabeticOrUnderscoreOrHyphen> = JSRCompatibleFactory.factory;

export type AlphabeticOrUnderscoreOrHyphenString = typeof type;
export const AlphabeticOrUnderscoreOrHyphenString = factory;
```

Not like, worse than human trafficking or using your AC when it's only 26°C but... still.

**Comment by masonmark** [comment]
OK, I'll "do it" **provided** that [Windsurf](https://codeium.com/windsurf) can do the actual doing of it... 😆 

<img width="687" alt="image" src="https://github.com/user-attachments/assets/833d1672-a08d-48ce-aa87-a22f83e42faa" />

**Comment by protiev** [comment]
haha haha you right, this is [lame](https://github.com/axhxrx/validated-string/actions/runs/12330449197/job/34415932011)

maybe there is way to dry-run? i'm in the pub^Wdiscotheque so i cant check atm

**Comment by protiev** [comment]
@masonmark `DAT WERX?` 

reference https://jsr.io/@axhxrx/validated-string/score

may i finally acquiesce to the multitudinous dance invitations i am receiving or would you be needing something else

**Comment by masonmark** [comment]
Well can you update the easy fields to rev up the JSR score? Should be doable from your phone. Then I will close this.

**Comment by protiev** [comment]
ok i fix everything except `ERR_MASONMARK_NOT_WRITE_ENOUGH_DOCS`

good luck with it señor

**Comment by masonmark** [comment]
🫡 roger that
